spring:
  application:
    name: meritoEstudantil
  
  datasource:
    url: jdbc:mysql://localhost:3306/MeritoEstudantil?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-to-a-long-random-string-minimum-32-chars}
    expiration-seconds: 3600

admin:
  gerente:
    email: admin@merito.com
    senha: admin123

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    lab.dev.meritoEstudantil: DEBUG
    io.jsonwebtoken: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  api-docs:
    path: /v3/api-docs

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://945651648511159:pj_bt_SFV4qOkpOs0TTCxfbzJfQ@dd3szshbo}
